version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '3306:3306'
    environment:
      - MARIADB_USER=exam
      - MARIADB_PASSWORD=exam
      - MARIADB_DATABASE=exam
      - MARIADB_ROOT_PASSWORD=exam
    volumes:
      - 'db-data:/bitnami/mariadb'
  quiz:
    build:
      context: .
    ports:
      - '90:90'
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=exam
      - DB_NAME=exam
      - DB_PASSWORD=exam
      - DOMAINNAME=195.201.234.139
    depends_on:
      - mariadb

volumes:
  db-data:
